# Project information
site_name: TensorFlow 文档中文翻译
#site_url:
repo_url: https://github.com/isaron/tfdocs.git
#repo_name:
#edit_uri:
site_description: 非官方文档
site_author: 黄传华(Arbor Huang)
#copyright:
#remote_branch: gh-pages
#remote_name: origin

# Documentation layout
pages:
    - 0. 首页: index.md
    - 1. 安装:
        - 1.1 综述: install/installing-tensorflow.md
        - 1.2 在Ubuntu上安装TensorFlow: install/installing-on-ubuntu.md
        - 1.3 在Mac OS X上安装TensorFlow: install/installing-on-mac.md
        - 1.4 在Windows上安装TensorFlow: install/installing-on-windows.md
        - 1.5 源代码安装TensorFlow: install/installing-from-sources.md
        - 1.6 迁移到TensorFlow 1.0: install/transitioning-to-1.0.md
    - 2. 开发:
        - 2.1 新手入门:
            - 2.1.1 TensorFlow快速入门: develop/getstarted/getting-started-with-tensorflow.md
            - 2.1.2 MNIST入门: develop/getstarted/mnist-for-ml-beginners.md
            - 2.1.3 MNIST进阶: develop/getstarted/deep-mnist-for-experts.md
            - 2.1.4 TensorFlow 运作方式 101: develop/getstarted/mechanics101.md
            - 2.1.5 tf.contrib.learn：快速开始: develop/getstarted/tf-contrib-learn-quickstart.md
            - 2.1.6 tf.contrib.learn：创建输入函数: develop/getstarted/tf-contrib-learn-function.md
            - 2.1.7 TensorBoard：可视化学习: develop/getstarted/tensorboard-visualizing-learning.md
            - 2.1.8 TensorBoard：内嵌可视化: develop/getstarted/tensorboard-embedding-visualization.md
            - 2.1.9 TensorBoard：图表可视化: develop/getstarted/tensorboard-graph-visualization.md
            - 2.1.10 tf.contrib.learn：日志和监控基础: develop/getstarted/tf-contrib-learn-logging-and-monitoring.md
        - 2.2 程序员手册:
            - 2.2.1 读取数据: develop/programmer/reading-data.md
            - 2.2.2 线程和队列: develop/programmer/threading-and-queues.md
            - 2.2.3 共享参数: develop/programmer/sharing-variables.md
            - 2.2.4 TensorFlow的版本语义: develop/programmer/version-semantics.md
            - 2.2.5 TensorFlow数据版本化：GraphDefs and Checkpoints: develop/programmer/data-versioning-graphdefs-and-checkpoints.md
            - 2.2.6 Supervisor：Training Helper for Days-Long Trainings: develop/programmer/supervisor-training-helper.md
            - 2.2.7 TensorFlow Debugger (tfdbg) 命令行指南：MNIST: develop/programmer/tfdbg-cli-tutorial.md
            - 2.2.8 TensorFlow Debugger (tfdbg) 与 tf.contrib.learn 结合使用: develop/programmer/how-to-use-tfdbg-with-tf-contib-learn.md
            - 2.2.9 导入导出MetaGraph: develop/programmer/exporting-and-importing-metagraph.md
            - 2.2.10 常见问题: develop/programmer/frequently-asked-questions.md
            - 2.2.11 Tensor排名、形状和类型: develop/programmer/tensor-ranks-shapes-and-types.md
            - 2.2.12 变量：创建、初始化、保存和加载: develop/programmer/variables-creation-initialization-saving-and-loading.md
        - 2.3 教程:
            - 2.3.1 曼德布洛特(Mandelbrot)集合: develop/tutorials/mandelbrot-set.md
            - 2.3.2 偏微分方程(PDEs): develop/tutorials/partial-differential-equations.md
            - 2.3.3 卷积神经网络: develop/tutorials/convolutional-neural-networks.md
            - 2.3.4 图像识别: develop/tutorials/image-recognition.md
            - 2.3.5 如何训练 Inception’s Final Layer for New Categories: develop/tutorials/how-to-retrain-inceptions-final-layer-for-new-categories.md
            - 2.3.6 字词的向量表示: develop/tutorials/vector-representations-of-words.md
            - 2.3.7 递归神经网络: develop/tutorials/recurrent-neural-networks.md
            - 2.3.8 Sequence-to-Sequence 模型: develop/tutorials/sequence-to-sequence-models.md
            - 2.3.9 TF Layers 指南：创建卷积神经网络: develop/tutorials/a-guide-to-tf-layers-buiding-a-convolutional-neural-network.md
            - 2.3.10 大规模线性模型与 TensorFlow: develop/tutorials/large-scale-linear-models-with-tensorflow.md
            - 2.3.11 TensorFlow 线性模型指导: develop/tutorials/tensorflow-linear-model-tutorial.md
            - 2.3.12 TensorFlow 广度与深度学习指导: develop/tutorials/tensorflow-wide-deep-learning-tutorial.md
            - 2.3.13 使用 GPU: develop/tutorials/using-gpus.md
        - 2.4 性能优化:
            - 2.4.1 总览: develop/performance/performance.md
            - 2.4.2 XLA 概览: develop/performance/xla-overview.md
            - 2.4.3 广播语义: develop/performance/broadcasting-semantics.md
            - 2.4.4 开发新的 XLA 后端: develop/performance/developing-a-new-backend-for-xla.md
            - 2.4.5 使用 JIT 编译: develop/performance/using-jit-compilation.md
            - 2.4.6 运算语义: develop/performance/operation-semantics.md
            - 2.4.7 Shapes and Layout: develop/performance/shapes-and-layout.md
            - 2.4.8 使用 AOT 编译: develop/performance/using-aot-compilation.md
            - 2.4.9 如何量化神经网络: develop/performance/how-to-quantize-neural-networks-with-tensorflow.md
    - 3. API r1.0:
        - 3.1 概览 r1.0: apidoc/overview.md
        - 3.2 Python API r1.0: apidoc/python-api.md
        - 3.3 C++ API r1.0: apidoc/cpp-api.md
        - 3.4 Java API r1.0: apidoc/java-api.md
        - 3.5 Go API: apidoc/go-api.md
    - 4. 部署:
        - 4.1 在Hadoop上运行TensorFlow: deploy/how-to-run-tensorflow-on-hadoop.md
        - 4.2 分布式部署TensorFlow: deploy/distributed-tensorflow.md
        - 4.3 TensorFlow服务: deploy/tensorflow-serving.md
    - 5. 扩展:
        - 5.1 TensorFlow架构: extend/architecture.md
        - 5.2 添加新的 Op: extend/adding-a-new-op.md
        - 5.3 添加自定义文件系统插件: extend/adding-a-custom-filesystem-plugin.md
        - 5.4 TensorFlow翻译: extend/tensorflow-in-other-languages.md
        - 5.5 自定义数据读取: extend/custom-data-readers.md
        - 5.6 用 tf.contrib.learn 建立估量: extend/creating-estimators-in-tf-contrib.learn.md
        - 5.7 TensorFlow模型文件的工具开发者指南: extend/a-tool-developers-guide-to-tensorflow-model-files.md
    - 6. 资源:
        - 6.1 社区:
            - 6.1.1 编写TensorFlow文档: resource/community/writing-tensorflow-docs.md
            - 6.1.2 TensorFlow风格指南: resource/community/tensorflow-style-guide.md
        - 6.2 关于:
            - 6.2.1 更多TF相关资源: resource/about/additional.md
            - 6.2.2 TensorFlow白皮书: resource/about/whitepaper.md
            - 6.2.3 TensorFlow Uses: resource/about/tfuses.md
    - 7. 版本:
        - 7.1 TensorFlow版本列表: version/index.md
        - 7.2 master: version/master.md
        - 7.3 r1.0: version/r1.0.md
        - 7.4 r0.12: version/r0.12.md
        - 7.5 r0.11: version/r0.11.md
        - 7.6 r0.10: version/r0.10.md
    - 8. 本项目的说明:
        - 8.1 关于本文档: about/about-project.md
        - 8.2 更新记录: about/release-notes.md
        - 8.3 Contributing: about/contributing.md
        - 8.4 License: about/license.md

# Build directories
theme: readthedocs
theme_dir: custom_theme
# theme: null
# theme_dir: cinder
#docs_dir:
#site_dir:
extra_css: [extra.css]
#extra_javascript:
#extra_templates:
extra:
    version: 0.1
    links:
        - http://www.mkdocs.org
        - https://docs.readthedocs.org/en/latest/builds.html#mkdocs
        - https://huangch.me

# Preview controls
#use_directory_urls: true
#strict: false
#dev_addr: '127.0.0.1:8000'

# Formatting options
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
